# Generated by Django 5.1.5 on 2025-03-03 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_message_email_alter_message_text_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={},
        ),
    ]
